#!/bin/sh

xrandr --output DVI-D-0 --off --output HDMI-0 --off --output DP-0 --off --output DP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2 --off --output DP-3 --off --output USB-C-0 --off

xrandr --output DVI-D-0 --off --output HDMI-0 --off --output DP-0 --off --output DP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2 --mode 1920x1080 --pos 1920x0 --rotate left --output DP-3 --off --output USB-C-0 --off

killall polybar

MONITOR=DP-1 polybar primary &
MONITOR=DP-2 polybar secondary &
