#!/bin/bash

if [ -z $1 ]; then
    echo 'Error: no background option provided'
    exit 1
fi

if [ -z $2 ]; then
    echo 'Error: A background image was not specified'
    exit 1
fi

if [ $3 ]; then
    echo `realpath $3` > /home/zhelding/.cache/wal/wal-vert
fi

if [[ $(polybar -m | wc -l) == 3 ]]; then
    wallpaper_sequence="${2} ${2} ${3}"
else
    wallpaper_sequence="${2} ${3}"
fi

if [ $1 = "center" ]; then
    feh --bg-center $wallpaper_sequence
elif [ $1 = "fill" ]; then
    feh --bg-fill $wallpaper_sequence
elif [ $1 = "max" ]; then
    feh --bg-max $wallpaper_sequence
elif [ $1 = "scale" ]; then
    feh --bg-scale $wallpaper_sequence
elif [ $1 = "tile" ]; then
    feh --bg-tile $wallpaper_sequence
else
    echo 'Error:' $1 'is not a valid feh background option'
    exit 1
fi

if wal --backend haishoku -n -i $2; then
    :
else
    wal -n -i $2
fi
