#!/bin/bash

killall polybar

monitors="$(xrandr --listactivemonitors)"

if [[ $monitors == *"HDMI"* ]]; then
	xrandr --output HDMI2 --off --output HDMI1 --off --output DP1 --off \
	--output eDP1 --primary --mode 1366x768 --pos 0x0 --rotate normal \
	--output VIRTUAL1 --off
else
    xrandr --output HDMI2 --off --output HDMI1 --mode 1920x1080 --pos 0x0 \
    --rotate normal --output DP1 --off --output eDP1 --primary --mode \
    1366x768 --pos 1920x312 --rotate normal --output VIRTUAL1 --off
fi

i3-msg 'workspace 6'
i3-msg 'workspace 1'

polybar primary &>/dev/null &
polybar secondary &>/dev/null &
