#!/bin/bash

killall polybar

wallpaper="$(cat $HOME/.cache/wal/wal)"
wallpapervert="$(cat $HOME/.cache/wal/wal-vert)"

if [[ $(polybar -m | wc -l) == 3 ]]; then
    xrandr --output HDMI-2 --off --output HDMI-1 --off --output DP-1 --off \
    --output eDP-1 --primary --mode 1366x768 --pos 0x0 --rotate normal \
    --output VIRTUAL1 --off

    MONITOR=eDP-1 polybar primary &> /dev/null &
else
    xrandr --output eDP-1 --mode 1366x768 --pos 0x1152 --rotate normal --output \
    HDMI-1 --mode 1920x1080 --pos 3286x0 --rotate left --output DP-1 --primary \
    --mode 1920x1080 --pos 1366x840 --rotate normal --output HDMI-2 --off

    MONITOR=DP-1  polybar primary &> /dev/null &
    MONITOR=HDMI-1  polybar secondary &> /dev/null &
    MONITOR=eDP-1  polybar secondary &> /dev/null &
fi

set-wal scale $wallpaper $wallpapervert
